### PR TITLE
Fix RemovedInDjango19Warning

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Deals with https://github.com/HonzaKral/django-threadedcomments/issues/73

### CODE REVIEW

**Comment by vdboor** [comment]
Thanks, this seems like a good for the for `__init__.py` loading issue.

**Comment by vmarkovtsev** [comment]
@mrmachine, fixing the imports is just a matter of adding "models":

```Python
from threadedcomments.models import ThreadedComment
```

I guess it is kind of code Django creators want for every app.

**Comment by mrmachine** [comment]
@vmarkovtsev Yep. I was able to fix our project as you suggest. But `django-fluent-comments` is still broken (and possibly many other projects?), so we are just using an older version of `django-threadedcomments` for now.

I don't know if this change is required to prevent breakage when Django 1.9 hits, but messing around with imports like this can easily break downstream projects as we've discovered. Perhaps something like this would be more compatible with 1.9, without breaking downstream projects?

```
from django.apps import apps

ThreadedComment = apps.get_model('threadedcomments.ThreadedComment')
```

(I haven't tested this.)

**Comment by vmarkovtsev** [comment]
@mrmachine, just curious, what kind of project do you have?

Unfortunately, your suggested fix will not work, because at the time __init__ is interpreted, there is no such app, "threadedcomments". Actually, this is the very reason why one gets original warning. Please see the corresponding issue https://github.com/HonzaKral/django-threadedcomments/issues/73 for the motivation behind.

I am sorry that it breaks other projects. I've sent PR to fluent; if you know any similar, please write here, I will try to fix them too.

**Comment by mrmachine** [comment]
No problem. I don't doubt the fix is required and there's probably no better way to do it. Thanks for opening the PR on `django-fluent-comments`.

**Comment by vmarkovtsev** [comment]
@mrmachine, ThreadedCommentForm does model import, so it had to be removed, too.

**Pull request merged**
